# Generated by Django 3.2 on 2022-10-27 17:07

from django.db import migrations, models
import django.db.models.deletion
import storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storyboards', '0032_auto_20221026_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bordomatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='', verbose_name='Видео')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('fps', models.PositiveIntegerField(verbose_name='ФПС')),
                ('width', models.PositiveIntegerField(verbose_name='Длина')),
                ('height', models.PositiveIntegerField(verbose_name='Ширина')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboards.storyboard', verbose_name='Сториборд')),
            ],
        ),
        migrations.CreateModel(
            name='ImageForBordomaticPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Картинка')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('bordomatic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bordomatic.bordomatic', verbose_name='Картинка для бордоматика')),
            ],
        ),
        migrations.CreateModel(
            name='ImageForBordomatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='Картинка')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('bordomatic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bordomatic.bordomatic', verbose_name='Картинка для бордоматика')),
            ],
        ),
        migrations.CreateModel(
            name='BordomaticPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(storage=storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Видео')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboards.storyboard', verbose_name='Сториборд')),
            ],
        ),
        migrations.CreateModel(
            name='AudioForBordomaticPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(storage=storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Аудио')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('begin', models.TimeField(verbose_name='Начало')),
                ('end', models.TimeField(verbose_name='Конец')),
                ('volume', models.FloatField(verbose_name='Громкость')),
                ('bordomatic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bordomatic.bordomatic', verbose_name='Аудио для бордоматика')),
            ],
        ),
        migrations.CreateModel(
            name='AudioForBordomatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='', verbose_name='Аудио')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('begin', models.TimeField(verbose_name='Начало')),
                ('end', models.TimeField(verbose_name='Конец')),
                ('volume', models.FloatField(verbose_name='Громкость')),
                ('bordomatic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bordomatic.bordomatic', verbose_name='Аудио для бордоматика')),
            ],
        ),
    ]
