# Generated by Django 3.2 on 2022-11-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordomatic', '0002_auto_20221114_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioforbordomatic',
            name='bordomatic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='bordomatic.bordomatic', verbose_name='Аудио для бордоматика'),
        ),
        migrations.AlterField(
            model_name='audioforbordomaticprivate',
            name='bordomatic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='bordomatic.bordomaticprivate', verbose_name='Аудио для бордоматика (Приват)'),
        ),
        migrations.AlterField(
            model_name='imageforbordomatic',
            name='bordomatic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bordomatic.bordomatic', verbose_name='Картинка для бордоматика'),
        ),
        migrations.AlterField(
            model_name='imageforbordomaticprivate',
            name='bordomatic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bordomatic.bordomaticprivate', verbose_name='Картинка для бордоматика (Приват)'),
        ),
    ]
