# Generated by Django 3.2 on 2022-12-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordomatic', '0004_auto_20221115_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageforbordomatic',
            name='frame_time',
            field=models.PositiveIntegerField(default=2000, verbose_name='Время кадра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageforbordomaticprivate',
            name='frame_time',
            field=models.PositiveIntegerField(default=2000, verbose_name='Время кадра'),
            preserve_default=False,
        ),
    ]
