# Generated by Django 3.2 on 2022-12-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordomatic', '0005_auto_20221205_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bordomatic',
            options={'verbose_name': 'Бордоматик', 'verbose_name_plural': 'Бордоматики'},
        ),
        migrations.AlterModelOptions(
            name='bordomaticprivate',
            options={'verbose_name': 'Приватный бордоматик', 'verbose_name_plural': 'Приватные бордоматики'},
        ),
    ]
