# Generated by Django 3.2 on 2022-12-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordomatic', '0005_auto_20221205_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bordomatic',
            options={'verbose_name': 'Бордоматик', 'verbose_name_plural': 'Бордоматики'},
        ),
        migrations.AlterModelOptions(
            name='bordomaticprivate',
            options={'verbose_name': 'Приватный бордоматик', 'verbose_name_plural': 'Приватные бордоматики'},
        ),
        migrations.AddField(
            model_name='imageforbordomatic',
            name='effectName',
            field=models.CharField(blank=True, choices=[('zoomIn', 'zoomIn'), ('zoomOut', 'zoomOut'), ('moveTop', ' moveTop'), ('moveLeft', ' moveLeft'), ('moveRight', 'moveRight'), ('moveBottom', 'moveBottom')], max_length=30, null=True, verbose_name='Наименование эффекта'),
        ),
        migrations.AddField(
            model_name='imageforbordomatic',
            name='effectValue',
            field=models.CharField(blank=True, choices=[('1x', '1x'), ('2x', '2x'), ('3x', '3x'), ('4x', '4x'), ('5x', '5x'), ('6x', '6x'), ('7x', '7x'), ('8x', '8x'), ('9x', '9x'), ('10x', '10x'), ('11x', '11x'), ('12x', '12x'), ('13x', '13x'), ('14x', '14x'), ('15x', '15x'), ('16x', '16x'), ('17x', '17x'), ('18x', '18x'), ('19x', '19x'), ('20x', '20x'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], max_length=30, null=True, verbose_name='Парамер эффекта'),
        ),
        migrations.AddField(
            model_name='imageforbordomatic',
            name='subtitle',
            field=models.CharField(default=None, max_length=255, verbose_name='Субтитр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageforbordomatic',
            name='subtitleView',
            field=models.BooleanField(default=None, verbose_name='Парамер эффекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageforbordomaticprivate',
            name='effectName',
            field=models.CharField(blank=True, choices=[('zoomIn', 'zoomIn'), ('zoomOut', 'zoomOut'), ('moveTop', ' moveTop'), ('moveLeft', ' moveLeft'), ('moveRight', 'moveRight'), ('moveBottom', 'moveBottom')], max_length=30, null=True, verbose_name='Наименование эффекта'),
        ),
        migrations.AddField(
            model_name='imageforbordomaticprivate',
            name='effectValue',
            field=models.CharField(blank=True, choices=[('1x', '1x'), ('2x', '2x'), ('3x', '3x'), ('4x', '4x'), ('5x', '5x'), ('6x', '6x'), ('7x', '7x'), ('8x', '8x'), ('9x', '9x'), ('10x', '10x'), ('11x', '11x'), ('12x', '12x'), ('13x', '13x'), ('14x', '14x'), ('15x', '15x'), ('16x', '16x'), ('17x', '17x'), ('18x', '18x'), ('19x', '19x'), ('20x', '20x'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], max_length=30, null=True, verbose_name='Парамер эффекта'),
        ),
        migrations.AddField(
            model_name='imageforbordomaticprivate',
            name='subtitle',
            field=models.CharField(default=None, max_length=255, verbose_name='Субтитр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageforbordomaticprivate',
            name='subtitleView',
            field=models.BooleanField(default=None, max_length=255, verbose_name='Парамер эффекта'),
            preserve_default=False,
        ),
    ]
