# Generated by Django 3.2 on 2022-12-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordomatic', '0006_auto_20221208_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageforbordomatic',
            name='effectValue',
            field=models.CharField(blank=True, choices=[('1x', '1x'), ('2x', '2x'), ('3x', '3x'), ('4x', '4x'), ('5x', '5x'), ('6x', '6x'), ('7x', '7x'), ('8x', '8x'), ('9x', '9x'), ('10x', '10x'), ('11x', '11x'), ('12x', '12x'), ('13x', '13x'), ('14x', '14x'), ('15x', '15x'), ('16x', '16x'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], max_length=30, null=True, verbose_name='Парамер эффекта'),
        ),
        migrations.AlterField(
            model_name='imageforbordomaticprivate',
            name='effectValue',
            field=models.CharField(blank=True, choices=[('1x', '1x'), ('2x', '2x'), ('3x', '3x'), ('4x', '4x'), ('5x', '5x'), ('6x', '6x'), ('7x', '7x'), ('8x', '8x'), ('9x', '9x'), ('10x', '10x'), ('11x', '11x'), ('12x', '12x'), ('13x', '13x'), ('14x', '14x'), ('15x', '15x'), ('16x', '16x'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], max_length=30, null=True, verbose_name='Парамер эффекта'),
        ),
    ]
