# Generated by Django 3.2 on 2022-12-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordomatic', '0006_auto_20221212_1016'),
        ('bordomatic', '0007_auto_20221211_1723'),
    ]

    operations = [
    ]
