# Generated by Django 3.2 on 2022-12-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordomatic', '0008_merge_0006_auto_20221212_1016_0007_auto_20221211_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioforbordomatic',
            name='name_audio',
            field=models.CharField(default='audio_name.mp3', max_length=255, verbose_name='Имя аудиофайла'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audioforbordomaticprivate',
            name='name_audio',
            field=models.CharField(default='audio_name.mp3', max_length=255, verbose_name='Имя аудиофайла'),
            preserve_default=False,
        ),
    ]
