---
version: '2.4'
services:
  auditor-v2-nginx:
    # image: ${CI_REGISTRY_IMAGE}:latest
    build: nginx
    container_name: main_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - shared_web_root:/var/www/html
    networks:
      - home
  auditor-v2-api:
    user: app:app
    container_name: auditor-v2-api
    hostname: auditor-v2-api
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        APP_API_LOG: /app/backend/src/logs/apilog.log
    entrypoint: /app/docker/backend/wsgi-entrypoint.sh
    env_file:
      - .env.local
    volumes:
      - .:/app/
    depends_on:
      - auditor-v2-postgres
      - auditor-v2-source
    networks:
      - home
    ports:
      - 8000:8000
    healthcheck:
      test: curl -s -I --fail http://0.0.0.0:8000/ht/
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  auditor-v2-postgres:
    container_name: auditor-v2-postgres
    hostname: auditor-v2-postgres
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/app/pgdata/
    volumes:
      - pgdata:/var/lib/postgresql/data/app/
    depends_on:
      - auditor-v2-source
    healthcheck:
       test: pg_isready -U postgres -d postgres
       interval: 10s
       timeout: 5s
       retries: 5
       start_period: 10s
    # ports:
      # - 5432:5432
    networks:
      - home
  auditor-v2-redis:
    image: redis:6.2.6
    container_name: auditor-v2-redis
    hostname: auditor-v2-redis
    networks:
      - home

  auditor-v2-celery:
    user: app:app
    image: auditor-v2-celery
    container_name: auditor-v2-celery
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        APP_API_LOG: /app/backend/src/logs/apilog.log
    entrypoint: /app/docker/backend/celery-entrypoint.sh
    env_file:
      - .env.local
    volumes:
      - .:/app/
    depends_on:
      - auditor-v2-redis
      - auditor-v2-source
    networks:
      - home
  auditor-v2-source:
    image: ubuntu
    entrypoint: /app/docker/backend/source-entrypoint.sh
    volumes:
      - .:/app

volumes:
  pgdata: {}
  shared_web_root: {}
networks:
  home: {}
