# Generated by Django 3.2 on 2022-06-01 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=50)),
                ('doc_id', models.SmallIntegerField()),
                ('doc_name', models.CharField(max_length=100)),
                ('put_in_trash_by', models.EmailField(max_length=254, null=True)),
                ('in_trash_since', models.DateTimeField(auto_now_add=True)),
                ('host_project', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'km_trash',
                'unique_together': {('doc_type', 'doc_id')},
            },
        ),
    ]
