# Generated by Django 3.2 on 2022-06-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trash',
            table='ppm_trash',
        ),
    ]
