# Generated by Django 3.2 on 2022-06-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0002_alter_trash_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trash',
            options={'verbose_name': 'Recycle bin', 'verbose_name_plural': 'Recycle bin'},
        ),
    ]
