# Generated by Django 3.2 on 2022-06-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0003_alter_trash_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trash',
            name='host_project',
        ),
        migrations.AddField(
            model_name='trash',
            name='project_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trash',
            name='project_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trash',
            name='doc_id',
            field=models.BigIntegerField(),
        ),
    ]
