# Generated by Django 3.2 on 2022-10-20 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_auto_20221020_1827'),
        ('trash', '0005_auto_20220718_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='deleted_since',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Deleted since'),
        ),
        migrations.AlterField(
            model_name='trash',
            name='doc_id',
            field=models.BigIntegerField(verbose_name='Document id'),
        ),
        migrations.AlterField(
            model_name='trash',
            name='doc_name',
            field=models.CharField(max_length=100, verbose_name='Document name'),
        ),
        migrations.AlterField(
            model_name='trash',
            name='doc_type',
            field=models.CharField(max_length=50, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='trash',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='trash',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='trash',
            name='put_in_trash_by',
            field=models.EmailField(max_length=254, null=True, verbose_name='Put in trash by'),
        ),
    ]
