# Generated by Django 3.2 on 2022-10-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0006_auto_20221020_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trash',
        ),
    ]
