# Generated by Django 3.2 on 2023-03-27 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Last modified by')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('deleted_id', models.UUIDField(null=True, verbose_name='Deleted id')),
                ('deleted_since', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('template_text', models.TextField(default='', verbose_name='Template text')),
                ('example', models.TextField(default='', verbose_name='Example')),
                ('result', models.TextField(default='', verbose_name='Result')),
                ('is_common', models.BooleanField(default=False, verbose_name='Is common')),
                ('favourite', models.ManyToManyField(blank=True, related_name='favourite_templates', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'db_table': 'ppm_templates',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryForTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='Slug')),
                ('templates', models.ManyToManyField(blank=True, related_name='categories', to='catalog_templates.Template')),
            ],
            options={
                'db_table': 'ppm_templates_categories',
                'ordering': ['id'],
            },
        ),
    ]
