# Generated by Django 3.2 on 2022-06-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220613_0614'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='ppm_projects',
        ),
    ]
