# Generated by Django 3.2 on 2022-06-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='uid',
        ),
    ]
