# Generated by Django 3.2 on 2022-07-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
