# Generated by Django 3.2 on 2022-07-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_in_trash',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='in_trash_since',
            new_name='deleted_since',
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Deleted by'),
        ),
    ]
