# Generated by Django 3.2 on 2022-08-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20220718_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_id',
            field=models.UUIDField(null=True),
        ),
    ]
