# Generated by Django 3.2 on 2022-10-20 18:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_auto_20221020_1827'),
        ('projects', '0014_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=255, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='project',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='in_projects', to='contacts.Contact', verbose_name='Crew members'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='project',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='projects/logos/', verbose_name='Logo'),
        ),
    ]
