# Generated by Django 3.2 on 2022-10-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20221020_1827'),
        ('projects', '0015_file'),
    ]

    operations = [
    ]
