# Generated by Django 3.2 on 2022-10-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_merge_0015_auto_20221020_1827_0015_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='slugged_title',
        ),
    ]
