# Generated by Django 3.2 on 2022-10-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20221025_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slugged_name',
            field=models.SlugField(null=True, verbose_name='Filename'),
        ),
    ]
