# Generated by Django 3.2 on 2022-10-31 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_file_slugged_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['id']},
        ),
    ]
