# Generated by Django 3.2 on 2022-11-02 12:03

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20221031_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=utils.get_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.get_upload_path, verbose_name='Logo'),
        ),
    ]
