# Generated by Django 3.2 on 2022-11-15 08:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0022_auto_20221102_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Last modified by')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('deleted_id', models.UUIDField(null=True, verbose_name='Deleted id')),
                ('deleted_since', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('tag_color', models.CharField(blank=True, default='', max_length=20, verbose_name='Plate color')),
                ('frame_order', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order')),
                ('col_order', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order')),
                ('text', models.CharField(max_length=1000, verbose_name='Text')),
                ('host_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='projects.project')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
