# Generated by Django 3.2 on 2022-11-18 12:36

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='doc_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(null=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AddField(
            model_name='text',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
