# Generated by Django 3.2 on 2022-11-18 12:50

from django.db import migrations, models
import uuid


def gen_file_uuid(apps, schema_editor):
    MyModel = apps.get_model('projects', 'File')
    for row in MyModel.objects.all():
        row.order_id = uuid.uuid4()
        row.save(update_fields=['order_id'])


def gen_link_uuid(apps, schema_editor):
    MyModel = apps.get_model('projects', 'Link')
    for row in MyModel.objects.all():
        row.order_id = uuid.uuid4()
        row.save(update_fields=['order_id'])


def gen_text_uuid(apps, schema_editor):
    MyModel = apps.get_model('projects', 'Text')
    for row in MyModel.objects.all():
        row.order_id = uuid.uuid4()
        row.save(update_fields=['order_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20221118_1536'),
    ]

    operations = [
        migrations.RunPython(gen_text_uuid),
        migrations.RunPython(gen_link_uuid),
        migrations.RunPython(gen_file_uuid),
    ]
