# Generated by Django 3.2 on 2022-11-18 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20221118_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
