# Generated by Django 3.2 on 2022-11-23 12:49

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20221118_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=utils.get_doc_upload_path, verbose_name='File'),
        ),
    ]
