# Generated by Django 3.2 on 2022-11-29 09:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='link',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='text',
            name='frame_order',
        ),
        migrations.AddField(
            model_name='file',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='link',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='project',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='text',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
    ]
