# Generated by Django 3.2 on 2022-12-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20221129_0952'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'file', 'host_project')},
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('name', 'url', 'host_project')},
        ),
    ]
