# Generated by Django 3.2 on 2022-12-19 10:48

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_link_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='document_logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.get_doc_upload_path, verbose_name='Document logo'),
        ),
        migrations.AddField(
            model_name='link',
            name='document_logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.get_doc_upload_path, verbose_name='Document logo'),
        ),
        migrations.AddField(
            model_name='text',
            name='document_logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.get_doc_upload_path, verbose_name='Document logo'),
        ),
    ]
