# Generated by Django 3.2 on 2023-03-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20230214_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='host_project',
        ),
        migrations.RemoveField(
            model_name='text',
            name='host_project',
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='file',
            name='host_project',
        ),
    ]
