# Generated by Django 3.2 on 2022-06-28 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isTrial', models.BooleanField(default=False, verbose_name='Is trial')),
                ('tariffName', models.CharField(max_length=100, verbose_name='Tariff name')),
                ('tariffDescription', models.TextField(verbose_name='Tariff description')),
                ('baseMonthPrice', models.IntegerField(verbose_name='Base price/month')),
                ('paymentDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='subscription.paymentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='TariffPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthAmount', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Subscription period')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='subscription.tariff', verbose_name='Tariff')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endDate', models.BigIntegerField(verbose_name='Subscription end date')),
                ('recurrent', models.BooleanField(default=False, verbose_name='Recurrent active')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.tariff', verbose_name='Tariff')),
                ('tariffs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.paymentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(choices=[('card', 'Credit/debit card'), ('bill', 'Invoce')], max_length=4, verbose_name='Payment method')),
                ('paymentDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='subscription.paymentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Inn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Tax payer id')),
                ('title', models.CharField(max_length=255, verbose_name='Tax payer title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Russian rouble')], max_length=5, verbose_name='Currency')),
                ('currencyIcon', models.CharField(max_length=2, verbose_name='Currency icon')),
                ('paymentDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='subscription.paymentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('daysAmount', models.IntegerField(default=1, verbose_name='Subscription period')),
                ('summ', models.IntegerField()),
                ('isPaid', models.BooleanField(default=False, verbose_name='Payment complete')),
                ('number', models.IntegerField(default=0, verbose_name='Payment number')),
                ('recurrent', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.currency')),
                ('promocode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.promocode')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardPayments', to='subscription.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('daysAmount', models.IntegerField(default=1, verbose_name='Subscription period')),
                ('summ', models.IntegerField()),
                ('isPaid', models.BooleanField(default=False, verbose_name='Payment complete')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice title')),
                ('file', models.FileField(blank=True, null=True, upload_to='invoces/', verbose_name='Invoice file')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.currency')),
                ('promocode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.promocode')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankTransfers', to='subscription.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
