# Generated by Django 3.2 on 2022-07-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_paymentmethod_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransfer',
            old_name='daysAmount',
            new_name='days_amount',
        ),
        migrations.RenameField(
            model_name='banktransfer',
            old_name='isPaid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='cardpayment',
            old_name='daysAmount',
            new_name='days_amount',
        ),
        migrations.RenameField(
            model_name='cardpayment',
            old_name='isPaid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='currencyIcon',
            new_name='currency_icon',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='paymentDetails',
            new_name='payment_details',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='paymentDetails',
            new_name='payment_details',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='paymentMethod',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='tariff',
            old_name='baseMonthPrice',
            new_name='base_month_price',
        ),
        migrations.RenameField(
            model_name='tariff',
            old_name='isTrial',
            new_name='is_trial',
        ),
        migrations.RenameField(
            model_name='tariff',
            old_name='paymentDetails',
            new_name='payment_details',
        ),
        migrations.RenameField(
            model_name='tariff',
            old_name='tariffDescription',
            new_name='tariff_description',
        ),
        migrations.RenameField(
            model_name='tariff',
            old_name='tariffName',
            new_name='tariff_name',
        ),
        migrations.RenameField(
            model_name='tariffperiod',
            old_name='monthAmount',
            new_name='month_amount',
        ),
    ]
