# Generated by Django 3.2 on 2022-07-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20220702_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfers', to='subscription.subscription'),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payments', to='subscription.subscription'),
        ),
    ]
