# Generated by Django 3.2 on 2022-07-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20220704_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransfer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cardpayment',
            name='date',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.BigIntegerField(verbose_name='Subscription end timestamp'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.tariff'),
        ),
    ]
