# Generated by Django 3.2 on 2022-07-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_auto_20220704_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='payment_id',
            field=models.BigIntegerField(default=0, verbose_name='Payment ID'),
        ),
    ]
