# Generated by Django 3.2 on 2022-07-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_cardpayment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='end_timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promocode',
            name='start_timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tariffperiod',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Discount'),
        ),
    ]
