# Generated by Django 3.2 on 2022-08-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_subscription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinkoffResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TerminalKey', models.CharField(max_length=255)),
                ('OrderId', models.CharField(max_length=255)),
                ('Success', models.BooleanField()),
                ('Status', models.CharField(max_length=255)),
                ('PaymentId', models.PositiveBigIntegerField()),
                ('ErrorCode', models.CharField(max_length=255)),
                ('Amount', models.IntegerField()),
                ('CardId', models.IntegerField()),
                ('Pan', models.CharField(max_length=255)),
                ('ExpDate', models.CharField(max_length=4)),
                ('Token', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='cardpayment',
            name='number',
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='payment_id',
            field=models.BigIntegerField(verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tariff_description',
            field=models.TextField(max_length=1000, verbose_name='Tariff description'),
        ),
    ]
