# Generated by Django 3.2 on 2022-09-02 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_auto_20220829_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='banktransfer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='banktransfer',
            name='days_amount',
        ),
        migrations.RemoveField(
            model_name='cardpayment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cardpayment',
            name='days_amount',
        ),
        migrations.RemoveField(
            model_name='cardpayment',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='created_at',
            field=models.BigIntegerField(null=True, verbose_name='Payment timestamp'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='paid_at',
            field=models.DateTimeField(null=True, verbose_name='Paid at'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='period',
            field=models.IntegerField(null=True, verbose_name='Subscription period end'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='OrderId',
            field=models.UUIDField(default=uuid.UUID('6f047e41-2424-49ad-af61-973cb96ee4a2')),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='created_at',
            field=models.BigIntegerField(null=True, verbose_name='Payment timestamp'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='paid_at',
            field=models.DateTimeField(null=True, verbose_name='Paid at'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='period',
            field=models.IntegerField(null=True, verbose_name='Subscription period end'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscription.currency'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.promocode', to_field='code'),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscription.currency'),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.promocode', to_field='code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Russian rouble')], default=('RUB', 'Russian rouble'), max_length=5, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_icon',
            field=models.CharField(default='₽', max_length=2, verbose_name='Currency icon'),
        ),
        migrations.AlterField(
            model_name='tinkoffresponse',
            name='Amount',
            field=models.IntegerField(verbose_name='Сумма (коп.)'),
        ),
        migrations.AlterField(
            model_name='tinkoffresponse',
            name='CardId',
            field=models.IntegerField(verbose_name='ID карты'),
        ),
        migrations.AlterField(
            model_name='tinkoffresponse',
            name='ErrorCode',
            field=models.CharField(max_length=255, verbose_name='Код ошибки'),
        ),
        migrations.AlterField(
            model_name='tinkoffresponse',
            name='ExpDate',
            field=models.CharField(max_length=4, verbose_name='Срок действия карты'),
        ),
        migrations.AlterField(
            model_name='tinkoffresponse',
            name='OrderId',
            field=models.UUIDField(verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='tinkoffresponse',
            name='Pan',
            field=models.CharField(max_length=255, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='tinkoffresponse',
            name='PaymentId',
            field=models.PositiveBigIntegerField(verbose_name='ID платежа'),
        ),
        migrations.AlterField(
            model_name='tinkoffresponse',
            name='Status',
            field=models.CharField(max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tinkoffresponse',
            name='Success',
            field=models.BooleanField(verbose_name='Выполнен'),
        ),
        migrations.AlterField(
            model_name='tinkoffresponse',
            name='TerminalKey',
            field=models.CharField(max_length=255, verbose_name='Номер терминала'),
        ),
        migrations.AlterField(
            model_name='tinkoffresponse',
            name='Token',
            field=models.CharField(max_length=255, verbose_name='Подпись'),
        ),
    ]
