# Generated by Django 3.2 on 2022-09-02 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_auto_20220902_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='created_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='created_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='OrderId',
            field=models.UUIDField(default=uuid.UUID('c37996e9-26d3-4e51-a910-3692e6312003')),
        ),
    ]
