# Generated by Django 3.2 on 2022-09-04 03:21

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_alter_cardpayment_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='end_timestamp',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='start_timestamp',
        ),
        migrations.AddField(
            model_name='promocode',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='promocode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='OrderId',
            field=models.UUIDField(default=uuid.UUID('6410bde2-c605-4f1d-9be2-67c6ffd329fa')),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='promocode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='recurrent',
            field=models.BooleanField(default=True),
        ),
    ]
