# Generated by Django 3.2 on 2022-09-05 04:12

from django.db import migrations, models
import subscription.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0016_auto_20220904_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='month_qty',
            field=models.SmallIntegerField(default=1, verbose_name='Month qty'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='month_qty',
            field=models.SmallIntegerField(default=1, verbose_name='Month qty'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=subscription.models.get_invoice_path, verbose_name='Invoice file'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='promocode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo-code'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='summ',
            field=models.IntegerField(verbose_name='Order total'),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='OrderId',
            field=models.UUIDField(default=uuid.UUID('93e6a01b-1343-448f-8cbb-4265688dfb5e')),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='promocode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo-code'),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='summ',
            field=models.IntegerField(verbose_name='Order total'),
        ),
    ]
