# Generated by Django 3.2 on 2022-09-05 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0017_auto_20220905_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='OrderId',
            field=models.UUIDField(default=uuid.UUID('c72f6ef2-539e-42d9-9518-2bab0b5381ac')),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
