# Generated by Django 3.2 on 2022-09-05 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0018_auto_20220905_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpayment',
            name='OrderId',
            field=models.UUIDField(default=uuid.UUID('a1672a06-5c1a-40e9-90bb-1d19313915b4')),
        ),
    ]
