# Generated by Django 3.2 on 2022-09-09 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0019_alter_cardpayment_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpayment',
            name='OrderId',
            field=models.UUIDField(default=uuid.UUID('ce01227c-6ecd-4118-9a6a-dd4bb7d5197c')),
        ),
    ]
