# Generated by Django 3.2 on 2022-09-09 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0020_alter_cardpayment_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpayment',
            name='OrderId',
            field=models.UUIDField(default=uuid.UUID('0dd27dbe-22ae-4382-8cd2-08034f410cbc')),
        ),
    ]
