# Generated by Django 3.2 on 2022-09-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0023_auto_20220912_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pay_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='OrderId',
            field=models.UUIDField(auto_created=True),
        ),
    ]
