# Generated by Django 3.2 on 2022-10-20 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('subscription', '0027_auto_20221019_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscription.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='promocode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promocode'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfers', to='subscription.subscription', verbose_name='Subscription'),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscription.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='promocode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promocode'),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='recurrent',
            field=models.BooleanField(default=True, verbose_name='Recurrent'),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payments', to='subscription.subscription', verbose_name='Subscription'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='subscription.paymentdetails', verbose_name='Payment details'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.FloatField(default=0.0, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='end',
            field=models.DateField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start',
            field=models.DateField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pay_day',
            field=models.DateField(null=True, verbose_name='Pay day'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='recurrent_payment_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask', verbose_name='Recurrent payment task'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tariffs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.paymentdetails', verbose_name='Payment details'),
        ),
        migrations.AlterField(
            model_name='tpi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpids', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
