# Generated by Django 3.2 on 2022-11-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0028_auto_20221020_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='School name')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.AddField(
            model_name='promocode',
            name='amount_of_use',
            field=models.IntegerField(default=0, verbose_name='Amount of use'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Student promocod'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='tariff_period',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Tariff period'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Student tariff'),
        ),
        migrations.CreateModel(
            name='SertificatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertificate_payments', to='subscription.promocode', verbose_name='Promocode')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertificate_payments', to='subscription.subscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Students promocode payment',
                'verbose_name_plural': 'Students promocode payments',
            },
        ),
        migrations.AddField(
            model_name='promocode',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='subscription.school', verbose_name='School'),
        ),
    ]
