# Generated by Django 3.2 on 2022-11-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0030_auto_20221117_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='total_usage',
            field=models.IntegerField(default=0, verbose_name='Total usage'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Student promocode'),
        ),
    ]
