# Generated by Django 3.2 on 2023-02-14 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('timing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='folders.folder', verbose_name='Folder'),
        ),
    ]
