# Generated by Django 3.2 on 2023-02-27 07:50

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0026_auto_20230222_0742'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Last modified by')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('deleted_id', models.UUIDField(null=True, verbose_name='Deleted id')),
                ('deleted_since', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('tag_color', models.CharField(blank=True, default='', max_length=20, verbose_name='Plate color')),
                ('data_row_order', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order')),
                ('col_order', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order')),
                ('host_document_id', models.IntegerField(blank=True, null=True, verbose_name='Host document id')),
                ('host_document_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Host document model')),
                ('frame_columns', models.ManyToManyField(blank=True, related_name='of_default_table', to='common.UserColumn', verbose_name='Frame columns')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'default_table',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DefaultTableFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Last modified by')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('deleted_id', models.UUIDField(null=True, verbose_name='Deleted id')),
                ('deleted_since', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('tag_color', models.CharField(blank=True, default='', max_length=20, verbose_name='Plate color')),
                ('data_row_order', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order')),
                ('col_order', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order')),
                ('host_default_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_frames', to='table.defaulttablemodel', verbose_name='Table')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('userfields', models.ManyToManyField(blank=True, related_name='of_table_frame', to='common.UserCell')),
            ],
            options={
                'verbose_name': 'Tableframe',
                'verbose_name_plural': 'Tableframes',
                'db_table': 'table_frames',
                'ordering': ['id'],
            },
        ),
    ]
