# Generated by Django 3.2 on 2023-03-10 06:14
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20230310_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttablemodel',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),)
    ]
