# Generated by Django 3.2 on 2023-03-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_defaulttableusercell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttableframe',
            name='userfields',
            field=models.ManyToManyField(blank=True, related_name='of_table_frame', to='table.DefaultTableUsercell'),
        ),
    ]
