# Generated by Django 3.2 on 2023-03-21 05:48

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table', '0007_alter_defaulttableframe_userfields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaulttablemodel',
            old_name='host_folder',
            new_name='folder',
        ),
        migrations.CreateModel(
            name='UsercellFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='usercell_files/')),
                ('host_usercell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='table.defaulttableusercell')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, accounts.models.ResizeImageMixin),
        ),
    ]
