# Generated by Django 3.2 on 2022-06-01 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('storyboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shootingplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sortOrder', models.PositiveBigIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('in_trash_since', models.DateTimeField(blank=True, null=True)),
                ('tagColor', models.CharField(blank=True, default='', max_length=20)),
                ('date', models.DateField()),
                ('host_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shootingplans', to='projects.project')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'km_shootingplans',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sortOrder', models.PositiveBigIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('in_trash_since', models.DateTimeField(blank=True, null=True)),
                ('tagColor', models.CharField(blank=True, default='', max_length=20)),
                ('day_start', models.TimeField(null=True)),
                ('host_shootingplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shp_units', to='shootingplans.shootingplan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'km_shp_units',
            },
        ),
        migrations.CreateModel(
            name='ShpFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sortOrder', models.PositiveBigIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('in_trash_since', models.DateTimeField(blank=True, null=True)),
                ('tagColor', models.CharField(blank=True, default='', max_length=20)),
                ('duration', models.TimeField(null=True)),
                ('host_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shpu_frames', to='shootingplans.unit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sbd_frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storyboards.frame')),
            ],
            options={
                'db_table': 'km_shp_frames',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sortOrder', models.PositiveBigIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('in_trash_since', models.DateTimeField(blank=True, null=True)),
                ('tagColor', models.CharField(blank=True, default='', max_length=20)),
                ('duration', models.TimeField(null=True)),
                ('host_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shpu_processes', to='shootingplans.unit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'km_shp_processes',
            },
        ),
    ]
