# Generated by Django 3.2 on 2022-06-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shpframe',
            name='host_unit',
            field=models.ForeignKey(default=3,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='shpu_frames', to='shootingplans.unit'),
            preserve_default=False,
        ),
    ]
