# Generated by Django 3.2 on 2022-06-03 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0002_auto_20220603_0227'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shootingplans', '0002_alter_shpframe_host_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sortOrder', models.PositiveBigIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('in_trash_since', models.DateTimeField(blank=True, null=True)),
                ('tagColor', models.CharField(blank=True, default='', max_length=20)),
                ('duration', models.TimeField(null=True)),
            ],
            options={
                'db_table': 'km_unit_frames',
            },
        ),
        migrations.RemoveField(
            model_name='shpframe',
            name='host_unit',
        ),
        migrations.RemoveField(
            model_name='shpframe',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='shpframe',
            name='sbd_frame',
        ),
        migrations.AlterField(
            model_name='unit',
            name='day_start',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='host_shootingplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='shootingplans.shootingplan'),
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='ShpFrame',
        ),
        migrations.AddField(
            model_name='unitframe',
            name='host_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_frames', to='shootingplans.unit'),
        ),
        migrations.AddField(
            model_name='unitframe',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitframe',
            name='sbd_frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storyboards.frame'),
        ),
    ]
