# Generated by Django 3.2 on 2022-06-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0003_auto_20220603_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shootingplan',
            name='sortOrder',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='sortOrder',
        ),
        migrations.RemoveField(
            model_name='unitframe',
            name='sortOrder',
        ),
    ]
