# Generated by Django 3.2 on 2022-06-09 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0005_auto_20220608_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitframe',
            name='host_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitframes', to='shootingplans.unit'),
        ),
    ]
