# Generated by Django 3.2 on 2022-06-09 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0008_alter_chronoframe_sbdframe'),
        ('shootingplans', '0006_alter_unitframe_host_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitframe',
            name='sbd_frame',
        ),
        migrations.AddField(
            model_name='unitframe',
            name='sbdframe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_unitframes', to='storyboards.frame'),
        ),
    ]
