# Generated by Django 3.2 on 2022-06-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0007_auto_20220609_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitframe',
            name='duration',
            field=models.TimeField(default='00:00'),
        ),
    ]
