# Generated by Django 3.2 on 2022-06-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_userfieldmap_field'),
        ('shootingplans', '0008_alter_unitframe_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitframe',
            name='userfields',
            field=models.ManyToManyField(blank=True, to='common.UserFieldMap'),
        ),
    ]
