# Generated by Django 3.2 on 2022-06-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0009_unitframe_userfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(default='Unit', max_length=50),
        ),
        migrations.AlterModelTable(
            name='unitframe',
            table='km_shp_unitframes',
        ),
    ]
