# Generated by Django 3.2 on 2022-06-13 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0010_auto_20220612_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shootingplan',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='unitframe',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='shootingplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitframe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shootingplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shootingplan',
            name='in_trash_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='shootingplan',
            name='is_in_trash',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='shootingplan',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified at'),
        ),
        migrations.AlterField(
            model_name='shootingplan',
            name='last_modified_user',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='shootingplan',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='shootingplan',
            name='tagColor',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Plate color'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='in_trash_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_in_trash',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified at'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='last_modified_user',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='tagColor',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Plate color'),
        ),
        migrations.AlterField(
            model_name='unitframe',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unitframe',
            name='in_trash_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='unitframe',
            name='is_in_trash',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='unitframe',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified at'),
        ),
        migrations.AlterField(
            model_name='unitframe',
            name='last_modified_user',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='unitframe',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='unitframe',
            name='tagColor',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Plate color'),
        ),
    ]
