# Generated by Django 3.2 on 2022-06-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0011_auto_20220613_0614'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shootingplan',
            table='ppm_shootingplans',
        ),
        migrations.AlterModelTable(
            name='unit',
            table='ppm_shootingplans_units',
        ),
        migrations.AlterModelTable(
            name='unitframe',
            table='ppm_shootingplans_unitframes',
        ),
    ]
