# Generated by Django 3.2 on 2022-06-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_rename_field_usercell_column'),
        ('shootingplans', '0012_auto_20220613_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitframe',
            name='userfields',
            field=models.ManyToManyField(blank=True, related_name='of_unit', to='common.UserCell'),
        ),
    ]
