# Generated by Django 3.2 on 2022-06-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0014_unit_unitframe_columns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unitframe_columns',
            new_name='columns',
        ),
    ]
