# Generated by Django 3.2 on 2022-06-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20220618_1152'),
        ('shootingplans', '0016_rename_columns_unit_frame_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitframe',
            name='userfields',
            field=models.ManyToManyField(blank=True, related_name='of_unitframe', to='common.UserCell'),
        ),
    ]
