# Generated by Django 3.2 on 2022-06-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0017_alter_unitframe_userfields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='unitframe',
            options={'ordering': ['id']},
        ),
    ]
