# Generated by Django 3.2 on 2022-06-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0019_auto_20220625_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shootingplan',
            options={'verbose_name': 'Shootingplan', 'verbose_name_plural': 'Shootingplans'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['id'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterModelOptions(
            name='unitframe',
            options={'ordering': ['id'], 'verbose_name': 'Unit frame', 'verbose_name_plural': 'Unit frames'},
        ),
    ]
