# Generated by Django 3.2 on 2022-08-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0023_auto_20220816_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shootingplan',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(default='Юнит', max_length=50),
        ),
        migrations.AlterField(
            model_name='unitframe',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
    ]
