# Generated by Django 3.2 on 2022-10-31 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0026_shootingplan_doc_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shootingplan',
            options={'ordering': ['id'], 'verbose_name': 'Shootingplan', 'verbose_name_plural': 'Shootingplans'},
        ),
    ]
