# Generated by Django 3.2 on 2022-11-18 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0029_auto_20221118_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shootingplan',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
