# Generated by Django 3.2 on 2022-11-29 09:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootingplans', '0030_auto_20221118_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shootingplan',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='unitframe',
            name='frame_order',
        ),
        migrations.AddField(
            model_name='shootingplan',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='unit',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='unitframe',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
    ]
