# Generated by Django 3.2 on 2022-06-01 05:16

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chrono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sortOrder', models.PositiveBigIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('in_trash_since', models.DateTimeField(blank=True, null=True)),
                ('tagColor', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'km_sb_chronos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sortOrder', models.PositiveBigIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('in_trash_since', models.DateTimeField(blank=True, null=True)),
                ('tagColor', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'km_sb_frames',
                'ordering': ['sortOrder', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Storyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sortOrder', models.PositiveBigIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('in_trash_since', models.DateTimeField(blank=True, null=True)),
                ('tagColor', models.CharField(blank=True, default='', max_length=20)),
                ('frameOrder', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None)),
                ('colOrder', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None)),
                ('host_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyboards', to='projects.project')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'km_storyboards',
                'ordering': ['sortOrder', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sortOrder', models.PositiveBigIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('in_trash_since', models.DateTimeField(blank=True, null=True)),
                ('tagColor', models.CharField(blank=True, default='', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='storyboards/shots/')),
                ('host_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='storyboards.frame')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'km_sb_shots',
            },
        ),
        migrations.AddField(
            model_name='frame',
            name='host_storyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbd_frames', to='storyboards.storyboard'),
        ),
        migrations.AddField(
            model_name='frame',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frame',
            name='userfields',
            field=models.ManyToManyField(blank=True, to='common.UserFieldMap'),
        ),
        migrations.CreateModel(
            name='ChronoFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sortOrder', models.PositiveBigIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('in_trash_since', models.DateTimeField(blank=True, null=True)),
                ('tagColor', models.CharField(blank=True, default='', max_length=20)),
                ('host_chrono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboards.chrono')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sbdframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboards.frame')),
            ],
            options={
                'db_table': 'km_chr_frm',
                'ordering': ['sortOrder', 'id'],
            },
        ),
        migrations.AddField(
            model_name='chrono',
            name='frames',
            field=models.ManyToManyField(blank=True, through='storyboards.ChronoFrame', to='storyboards.Frame'),
        ),
        migrations.AddField(
            model_name='chrono',
            name='host_storyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronos', to='storyboards.storyboard'),
        ),
        migrations.AddField(
            model_name='chrono',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
