# Generated by Django 3.2 on 2022-06-04 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storyboards', '0004_auto_20220604_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronoFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('in_trash_since', models.DateTimeField(blank=True, null=True)),
                ('tagColor', models.CharField(blank=True, default='', max_length=20)),
                ('chrono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronoframes', to='storyboards.chrono')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sbdframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_chronos', to='storyboards.frame')),
            ],
            options={
                'db_table': 'km_chr_frm',
            },
        ),
    ]
