# Generated by Django 3.2 on 2022-06-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0005_chronoframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chronoframe',
            old_name='chrono',
            new_name='host_chrono',
        ),
    ]
