# Generated by Django 3.2 on 2022-06-09 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0007_auto_20220608_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronoframe',
            name='sbdframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_chronframes', to='storyboards.frame'),
        ),
    ]
