# Generated by Django 3.2 on 2022-06-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0008_alter_chronoframe_sbdframe'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chronoframe',
            table='km_sb_chronoframes',
        ),
        migrations.AlterModelTable(
            name='shot',
            table='km_sb_frames_shots',
        ),
    ]
