# Generated by Django 3.2 on 2022-06-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0010_auto_20220613_0614'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chrono',
            table='ppm_storyboards_chronos',
        ),
        migrations.AlterModelTable(
            name='chronoframe',
            table='ppm_storyboards_chronoframes',
        ),
        migrations.AlterModelTable(
            name='frame',
            table='ppm_storyboards_frames',
        ),
        migrations.AlterModelTable(
            name='shot',
            table='ppm_storyboards_frames_shots',
        ),
        migrations.AlterModelTable(
            name='storyboard',
            table='ppm_storyboards',
        ),
    ]
