# Generated by Django 3.2 on 2022-06-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_rename_field_usercell_column'),
        ('storyboards', '0013_alter_frame_userfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='userfields',
            field=models.ManyToManyField(blank=True, related_name='of_frame', to='common.UserCell'),
        ),
    ]
