# Generated by Django 3.2 on 2022-06-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0015_storyboard_frame_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chronoframe',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='shot',
            options={'ordering': ['id']},
        ),
    ]
