# Generated by Django 3.2 on 2022-06-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0017_auto_20220625_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chrono',
            options={'ordering': ['id'], 'verbose_name': 'Footage version', 'verbose_name_plural': 'Footage versions'},
        ),
        migrations.AlterModelOptions(
            name='chronoframe',
            options={'ordering': ['id'], 'verbose_name': 'Footage frame', 'verbose_name_plural': 'Footage frames'},
        ),
        migrations.AlterModelOptions(
            name='frame',
            options={'ordering': ['id'], 'verbose_name': 'Frame', 'verbose_name_plural': 'Frames'},
        ),
        migrations.AlterModelOptions(
            name='shot',
            options={'ordering': ['id'], 'verbose_name': 'Shot', 'verbose_name_plural': 'Shots'},
        ),
        migrations.AlterModelOptions(
            name='storyboard',
            options={'ordering': ['id'], 'verbose_name': 'Storyboard', 'verbose_name_plural': 'Storyboards'},
        ),
    ]
