# Generated by Django 3.2 on 2022-06-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0018_auto_20220626_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='storyboards/shots/'),
        ),
    ]
