# Generated by Django 3.2 on 2022-07-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0020_auto_20220702_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chrono',
            old_name='is_in_trash',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='chrono',
            old_name='in_trash_since',
            new_name='deleted_since',
        ),
        migrations.RenameField(
            model_name='chronoframe',
            old_name='is_in_trash',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='chronoframe',
            old_name='in_trash_since',
            new_name='deleted_since',
        ),
        migrations.RenameField(
            model_name='frame',
            old_name='is_in_trash',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='frame',
            old_name='in_trash_since',
            new_name='deleted_since',
        ),
        migrations.RenameField(
            model_name='shot',
            old_name='is_in_trash',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='shot',
            old_name='in_trash_since',
            new_name='deleted_since',
        ),
        migrations.RenameField(
            model_name='storyboard',
            old_name='is_in_trash',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='storyboard',
            old_name='in_trash_since',
            new_name='deleted_since',
        ),
        migrations.AddField(
            model_name='chrono',
            name='deleted_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='chronoframe',
            name='deleted_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='frame',
            name='deleted_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='shot',
            name='deleted_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='storyboard',
            name='deleted_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Deleted by'),
        ),
    ]
