# Generated by Django 3.2 on 2022-08-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0021_auto_20220718_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chrono',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='chrono',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='chronoframe',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='chronoframe',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='storyboard',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='storyboard',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='chrono',
            name='deleted_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='chronoframe',
            name='deleted_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='deleted_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='deleted_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='storyboard',
            name='deleted_id',
            field=models.UUIDField(null=True),
        ),
    ]
