# Generated by Django 3.2 on 2022-08-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0022_auto_20220816_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='duration',
            field=models.TimeField(default='00:00'),
        ),
    ]
