# Generated by Django 3.2 on 2022-10-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0024_auto_20220829_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
