# Generated by Django 3.2 on 2022-10-20 19:23

from django.db import migrations, models
import django.db.models.deletion
import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0025_createdvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bordomatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='', verbose_name='Видео')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboards.storyboard', verbose_name='Сториборд')),
            ],
        ),
        migrations.CreateModel(
            name='BordomaticPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(storage=storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Видео')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboards.storyboard', verbose_name='Сториборд')),
            ],
        ),
        migrations.CreateModel(
            name='ImageForBordomatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='Картинка')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('bordomatic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboards.bordomatic', verbose_name='Картинка для бордоматика')),
            ],
        ),
        migrations.CreateModel(
            name='ImageForBordomaticPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Картинка')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('bordomatic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboards.bordomatic', verbose_name='Картинка для бордоматика')),
            ],
        ),
        migrations.DeleteModel(
            name='CreatedVideo',
        ),
    ]
