# Generated by Django 3.2 on 2022-10-20 18:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20221020_1827'),
        ('common', '0022_auto_20221020_1827'),
        ('storyboards', '0025_createdvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrono',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='chrono',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='chrono',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AlterField(
            model_name='chronoframe',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='chronoframe',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='chronoframe',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='host_storyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='storyboards.storyboard', verbose_name='Storyboard'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='storyboards/shots/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AlterField(
            model_name='storyboard',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='storyboard',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='storyboard',
            name='frame_columns',
            field=models.ManyToManyField(blank=True, related_name='of_storyboard', to='common.UserColumn', verbose_name='Frame columns'),
        ),
        migrations.AlterField(
            model_name='storyboard',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AlterField(
            model_name='storyboard',
            name='host_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyboards', to='projects.project', verbose_name='Project'),
        ),
    ]
