# Generated by Django 3.2 on 2022-10-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0026_auto_20221020_1827'),
        ('storyboards', '0026_auto_20221020_1923'),
    ]

    operations = [
    ]
