# Generated by Django 3.2 on 2022-10-21 21:48

from django.db import migrations, models
import django.db.models.deletion
import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0027_merge_0026_auto_20221020_1827_0026_auto_20221020_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioForBordomaticPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(storage=storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Аудио')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('bordomatic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboards.bordomatic', verbose_name='Аудио для бордоматика')),
            ],
        ),
        migrations.CreateModel(
            name='AudioForBordomatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='', verbose_name='Аудио')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('bordomatic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboards.bordomatic', verbose_name='Аудио для бордоматика')),
            ],
        ),
    ]
