# Generated by Django 3.2 on 2022-10-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0028_audioforbordomatic_audioforbordomaticprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioforbordomatic',
            name='begin',
            field=models.TimeField(verbose_name='Начало'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audioforbordomatic',
            name='end',
            field=models.TimeField(verbose_name='Конец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audioforbordomatic',
            name='volume',
            field=models.FloatField(verbose_name='Громкость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audioforbordomaticprivate',
            name='begin',
            field=models.TimeField(verbose_name='Начало'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audioforbordomaticprivate',
            name='end',
            field=models.TimeField(verbose_name='Конец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audioforbordomaticprivate',
            name='volume',
            field=models.FloatField(verbose_name='Громкость'),
            preserve_default=False,
        ),
    ]
