# Generated by Django 3.2 on 2022-10-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0029_auto_20221023_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordomatic',
            name='fps',
            field=models.PositiveIntegerField(default=1, verbose_name='ФПС'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bordomatic',
            name='height',
            field=models.PositiveIntegerField(default=1, verbose_name='Ширина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bordomatic',
            name='width',
            field=models.PositiveIntegerField(default=1, verbose_name='Длина'),
            preserve_default=False,
        ),
    ]
