# Generated by Django 3.2 on 2022-10-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0030_auto_20221023_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioforbordomaticprivate',
            name='bordomatic',
        ),
        migrations.RemoveField(
            model_name='bordomatic',
            name='storyboard',
        ),
        migrations.RemoveField(
            model_name='bordomaticprivate',
            name='storyboard',
        ),
        migrations.RemoveField(
            model_name='imageforbordomatic',
            name='bordomatic',
        ),
        migrations.RemoveField(
            model_name='imageforbordomaticprivate',
            name='bordomatic',
        ),
        migrations.DeleteModel(
            name='AudioForBordomatic',
        ),
        migrations.DeleteModel(
            name='AudioForBordomaticPrivate',
        ),
        migrations.DeleteModel(
            name='Bordomatic',
        ),
        migrations.DeleteModel(
            name='BordomaticPrivate',
        ),
        migrations.DeleteModel(
            name='ImageForBordomatic',
        ),
        migrations.DeleteModel(
            name='ImageForBordomaticPrivate',
        ),
    ]
