# Generated by Django 3.2 on 2022-10-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0031_auto_20221025_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyboard',
            name='doc_uuid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
