# Generated by Django 3.2 on 2022-11-02 12:03

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0032_auto_20221026_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=utils.get_upload_path, verbose_name='File'),
        ),
    ]
