# Generated by Django 3.2 on 2022-11-18 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0033_alter_shot_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyboard',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
