# Generated by Django 3.2 on 2022-11-18 13:02

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('storyboards', 'Storyboard')
    for row in MyModel.objects.all():
        row.order_id = uuid.uuid4()
        row.save(update_fields=['order_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0034_storyboard_order_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
