# Generated by Django 3.2 on 2022-11-18 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0035_auto_20221118_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyboard',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
