# Generated by Django 3.2 on 2022-11-29 09:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0037_alter_shot_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chrono',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='chronoframe',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='storyboard',
            name='frame_order',
        ),
        migrations.AddField(
            model_name='chrono',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='chronoframe',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='frame',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='shot',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='storyboard',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
    ]
