# Generated by Django 3.2 on 2023-03-16 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poll', '0005_auto_20230316_2329'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_variables', to='poll.poll')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('count_of_sent', models.IntegerField(blank=True, default=0, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='integration.telegramintegration')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleSheetIntegration',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='poll.poll', verbose_name='poll id')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('spreadsheet_id', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='spreadsheetId')),
                ('spreadsheet_url', models.URLField(blank=True, null=True, verbose_name='spreadsheet url')),
                ('row_count', models.PositiveIntegerField(default=1, verbose_name='row count')),
                ('survey_id', models.ManyToManyField(blank=True, to='poll.SurveyPassing', verbose_name='survey_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'GoogleSheetIntegration',
                'verbose_name_plural': 'GoogleSheetIntegrations',
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheet_credentials', jsonfield.fields.JSONField(blank=True, default='', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GSCredentials',
                'verbose_name_plural': 'GSCredentials',
            },
        ),
    ]
