# Generated by Django 3.2 on 2022-06-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_userfieldmap_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfieldmap',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='common.userfield'),
        ),
    ]
