# Generated by Django 3.2 on 2022-06-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_userfieldmap_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfield',
            name='columnType',
            field=models.CharField(choices=[('text', 'Text'), ('select', 'Select choice'), ('email', 'Email'), ('phone', 'Phone'), ('image', 'Image'), ('time', 'Time')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='userfield',
            table='km_usercolumns',
        ),
        migrations.AlterModelTable(
            name='userfieldmap',
            table='km_usercolumns_content',
        ),
    ]
