# Generated by Django 3.2 on 2022-06-18 07:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storyboards', '0012_alter_frame_userfields'),
        ('common', '0006_auto_20220613_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnName', models.CharField(max_length=30, verbose_name='Column title')),
                ('columnType', models.CharField(choices=[('text', 'Text'), ('select', 'Select choice'), ('email', 'Email'), ('phone', 'Phone'), ('image', 'Image'), ('time', 'Time')], max_length=10, verbose_name='Column type')),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, null=True, size=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ppm_usercolumn',
                'get_latest_by': 'id',
            },
        ),
        migrations.RenameModel(
            old_name='UserFieldMap',
            new_name='UserCell',
        ),
        migrations.DeleteModel(
            name='UserField',
        ),
        migrations.AlterField(
            model_name='usercell',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='common.usercolumn'),
        ),
    ]
