# Generated by Django 3.2 on 2022-06-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20220618_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercell',
            old_name='field',
            new_name='column',
        ),
    ]
