# Generated by Django 3.2 on 2022-06-18 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_rename_field_usercell_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercolumn',
            name='choices',
        ),
        migrations.AddField(
            model_name='usercell',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='userfield_images/'),
        ),
        migrations.AlterModelTable(
            name='usercell',
            table='ppm_usercolumns_contents',
        ),
        migrations.AlterModelTable(
            name='usercolumn',
            table='ppm_usercolumns',
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=100)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='common.usercolumn')),
            ],
            options={
                'db_table': 'ppm_usercolumns_choices',
            },
        ),
    ]
