# Generated by Django 3.2 on 2022-06-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_userchoice_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercolumn',
            options={'ordering': ['id']},
        ),
    ]
