# Generated by Django 3.2 on 2022-06-24 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20220622_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercell',
            name='choiceId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.userchoice'),
        ),
    ]
