# Generated by Django 3.2 on 2022-06-29 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20220625_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercell',
            name='file',
        ),
        migrations.CreateModel(
            name='UsercellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='usercell_images/')),
                ('usercell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='common.usercell')),
            ],
        ),
    ]
