# Generated by Django 3.2 on 2022-06-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20220629_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercellimage',
            old_name='usercell',
            new_name='host_usercell',
        ),
    ]
