# Generated by Django 3.2 on 2022-06-30 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_rename_usercell_usercellimage_host_usercell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchoice',
            old_name='column',
            new_name='host_column',
        ),
    ]
