# Generated by Django 3.2 on 2022-06-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_rename_column_userchoice_host_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercell',
            old_name='column',
            new_name='host_usercolumn',
        ),
        migrations.RenameField(
            model_name='userchoice',
            old_name='host_column',
            new_name='host_usercolumn',
        ),
    ]
