# Generated by Django 3.2 on 2022-08-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20220702_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercell',
            name='cell_content',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Content'),
        ),
    ]
