# Generated by Django 3.2 on 2022-10-20 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0021_alter_usercell_cell_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercell',
            name='choice_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.userchoice', verbose_name='Choice id'),
        ),
        migrations.AlterField(
            model_name='usercell',
            name='host_usercolumn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='common.usercolumn', verbose_name='User column'),
        ),
        migrations.AlterField(
            model_name='usercell',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='usercolumn',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
