# Generated by Django 3.2 on 2022-12-29 10:23

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20221020_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.ImageField(upload_to=utils.get_icon_upload_path, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='сreated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Standard icon',
                'verbose_name_plural': 'Standard icons',
                'ordering': ('id',),
            },
        ),
    ]
