# Generated by Django 3.2 on 2023-01-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_standardicon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardicon',
            options={'ordering': ('id',), 'verbose_name': 'Стандартная иконка', 'verbose_name_plural': 'Стандартные иконки'},
        ),
        migrations.AlterField(
            model_name='usercolumn',
            name='column_type',
            field=models.CharField(choices=[('text', 'Text'), ('select', 'Select choice'), ('multiselect', 'Multiselect choice'), ('email', 'Email'), ('phone', 'Phone'), ('image', 'Image'), ('time', 'Time'), ('contact', 'Contact')], max_length=11, verbose_name='Column type'),
        ),
    ]
