# Generated by Django 3.2 on 2023-01-20 14:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20230116_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercell',
            name='choices_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Choices id'),
        ),
    ]
