# Generated by Django 3.2 on 2022-06-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_userfieldmap_field'),
        ('contacts', '0002_auto_20220603_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='userfields',
            field=models.ManyToManyField(blank=True, to='common.UserFieldMap'),
        ),
    ]
