# Generated by Django 3.2 on 2022-06-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20220613_0736'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='callsheetcalltime',
            table='ppm_contacts_callsheets_calltime',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='ppm_contacts',
        ),
        migrations.AlterModelTable(
            name='department',
            table='ppm_contacts_departments',
        ),
        migrations.AlterModelTable(
            name='position',
            table='ppm_contacts_positions',
        ),
    ]
