# Generated by Django 3.2 on 2022-06-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20220613_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='userfields',
        ),
    ]
