# Generated by Django 3.2 on 2022-06-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_contact_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='tagColor',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='tagColor',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CallsheetCalltime',
        ),
    ]
