# Generated by Django 3.2 on 2022-06-25 14:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20220625_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['id'], 'verbose_name': 'Crew member', 'verbose_name_plural': 'Crew members'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['id'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name Surname'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.position', verbose_name='Position'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='colOrder'),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='Department', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='department',
            name='tagColor',
            field=models.CharField(blank=True, max_length=10, verbose_name='Plate color'),
        ),
        migrations.RemoveField(
            model_name='position',
            name='colOrder'
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(default='Position', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='position',
            name='tagColor',
            field=models.CharField(blank=True, max_length=10, verbose_name='Plate color'),
        ),
    ]
