# Generated by Django 3.2 on 2022-07-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_auto_20220625_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='colOrder',
            new_name='col_order',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='frameOrder',
            new_name='frame_order',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='tagColor',
            new_name='tag_color',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='colOrder',
            new_name='col_order',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='frameOrder',
            new_name='frame_order',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='tagColor',
            new_name='tag_color',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='colOrder',
            new_name='col_order',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='frameOrder',
            new_name='frame_order',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='tagColor',
            new_name='tag_color',
        ),
    ]
