# Generated by Django 3.2 on 2022-08-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_auto_20220829_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name Surname'),
        ),
    ]
