# Generated by Django 3.2 on 2022-09-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_auto_20220829_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='Department', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(default='Position', max_length=100, verbose_name='Title'),
        ),
    ]
