# Generated by Django 3.2 on 2022-10-20 18:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_auto_20220905_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AlterField(
            model_name='department',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='department',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='department',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AlterField(
            model_name='position',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='position',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='position',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
    ]
