# Generated by Django 3.2 on 2022-11-29 09:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_auto_20221020_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='department',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='position',
            name='frame_order',
        ),
        migrations.AddField(
            model_name='contact',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='department',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='position',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
    ]
