# Generated by Django 3.2 on 2023-02-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-id'], 'verbose_name_plural': 'polls'},
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='poll_id',
            new_name='id',
        ),
    ]
