# Generated by Django 3.2 on 2023-02-27 15:09

from django.db import migrations, models
import utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20230224_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='host_project',
        ),
        migrations.AddField(
            model_name='poll',
            name='document_logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.get_doc_upload_path, verbose_name='Document logo'),
        ),
        migrations.AddField(
            model_name='poll',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
