# Generated by Django 3.2 on 2023-03-14 23:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20230227_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionquestion',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalquestion',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freeanswer',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headingquestion',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manyfromlistquestion',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaquestion',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratingquestion',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yesnoquestion',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SectionQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(default='Question', max_length=100)),
                ('parent_id', models.UUIDField(blank=True, null=True)),
                ('order_id', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=512)),
                ('caption', models.CharField(max_length=255)),
                ('require', models.BooleanField(default=False)),
                ('mix_answers', models.BooleanField(default=False)),
                ('time_for_answer', models.BooleanField(default=False)),
                ('type_for_show', models.IntegerField(default=0)),
                ('title_image', models.CharField(default='', max_length=512)),
                ('resize_image', models.BooleanField(default=False)),
                ('test_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('section_id', models.UUIDField(default=uuid.uuid4)),
                ('poll', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
            options={
                'verbose_name_plural': 'poll_sections',
                'db_table': 'poll_question_section',
            },
        ),
        migrations.CreateModel(
            name='PageQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(default='Question', max_length=100)),
                ('parent_id', models.UUIDField(blank=True, null=True)),
                ('order_id', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=512)),
                ('caption', models.CharField(max_length=255)),
                ('require', models.BooleanField(default=False)),
                ('mix_answers', models.BooleanField(default=False)),
                ('time_for_answer', models.BooleanField(default=False)),
                ('type_for_show', models.IntegerField(default=0)),
                ('title_image', models.CharField(default='', max_length=512)),
                ('resize_image', models.BooleanField(default=False)),
                ('test_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_id', models.UUIDField(default=uuid.uuid4)),
                ('poll', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
            options={
                'verbose_name_plural': 'poll_pages',
                'db_table': 'poll_question_page',
            },
        ),
        migrations.AddIndex(
            model_name='sectionquestion',
            index=models.Index(fields=['poll'], name='poll_questi_poll_id_8af7fd_idx'),
        ),
        migrations.AddIndex(
            model_name='pagequestion',
            index=models.Index(fields=['poll'], name='poll_questi_poll_id_4ae20f_idx'),
        ),
    ]
