# Generated by Django 3.2 on 2023-03-16 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20230314_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagequestion',
            name='page_id',
            field=models.UUIDField(default=uuid.UUID('779ee965-d4ea-49b5-8cee-03ee6559ca24')),
        ),
        migrations.AlterField(
            model_name='sectionquestion',
            name='section_id',
            field=models.UUIDField(default=uuid.UUID('3713abda-0a92-40f9-a5c7-cc59cc172b25')),
        ),
    ]
