# Generated by Django 3.2 on 2023-03-21 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20230314_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(default='Question', max_length=100)),
                ('parent_id', models.UUIDField(blank=True, null=True)),
                ('order_id', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=512)),
                ('caption', models.CharField(max_length=255)),
                ('require', models.BooleanField(default=False)),
                ('mix_answers', models.BooleanField(default=False)),
                ('time_for_answer', models.BooleanField(default=False)),
                ('type_for_show', models.IntegerField(default=0)),
                ('title_image', models.CharField(default='', max_length=512)),
                ('resize_image', models.BooleanField(default=False)),
                ('test_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('number', models.FloatField(default='')),
                ('poll', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
            options={
                'verbose_name_plural': 'poll_number_questions',
                'db_table': 'poll_number_question',
            },
        ),
        migrations.CreateModel(
            name='DateQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(default='Question', max_length=100)),
                ('parent_id', models.UUIDField(blank=True, null=True)),
                ('order_id', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=512)),
                ('caption', models.CharField(max_length=255)),
                ('require', models.BooleanField(default=False)),
                ('mix_answers', models.BooleanField(default=False)),
                ('time_for_answer', models.BooleanField(default=False)),
                ('type_for_show', models.IntegerField(default=0)),
                ('title_image', models.CharField(default='', max_length=512)),
                ('resize_image', models.BooleanField(default=False)),
                ('test_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateTimeField(default='')),
                ('poll', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
            options={
                'verbose_name_plural': 'poll_date_questions',
                'db_table': 'poll_date_question',
            },
        ),
        migrations.AddIndex(
            model_name='numberquestion',
            index=models.Index(fields=['poll'], name='poll_number_poll_id_aa162e_idx'),
        ),
        migrations.AddIndex(
            model_name='datequestion',
            index=models.Index(fields=['poll'], name='poll_date_q_poll_id_8e0757_idx'),
        ),
    ]
