# Generated by Django 3.2 on 2023-03-27 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20230321_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswerquestion',
            name='checked',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='useranswerquestion',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='useranswerquestion',
            name='number',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='CheckQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(default='Question', max_length=100)),
                ('parent_id', models.UUIDField(blank=True, null=True)),
                ('order_id', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=512)),
                ('caption', models.CharField(max_length=255)),
                ('require', models.BooleanField(default=False)),
                ('mix_answers', models.BooleanField(default=False)),
                ('time_for_answer', models.BooleanField(default=False)),
                ('type_for_show', models.IntegerField(default=0)),
                ('title_image', models.CharField(default='', max_length=512)),
                ('resize_image', models.BooleanField(default=False)),
                ('test_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked', models.BooleanField(default=False)),
                ('poll', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
            options={
                'verbose_name_plural': 'poll_check_questions',
                'db_table': 'poll_check_question',
            },
        ),
        migrations.AddIndex(
            model_name='checkquestion',
            index=models.Index(fields=['poll'], name='poll_check__poll_id_183976_idx'),
        ),
    ]
