# Generated by Django 3.2 on 2023-04-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20230327_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='template_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
