# Generated by Django 3.2 on 2023-04-07 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_poll_template_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datequestion',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='numberquestion',
            name='number',
            field=models.FloatField(default=0.0),
        ),
    ]
