# Generated by Django 3.2 on 2023-04-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_auto_20230413_2249'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itemquestion',
            index=models.Index(fields=['item_set'], name='poll_questi_item_se_2fc990_idx'),
        ),
    ]
