# Generated by Django 3.2 on 2023-04-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_itemquestion_poll_questi_item_se_2fc990_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manyfromlistquestion',
            name='items',
        ),
        migrations.AddField(
            model_name='manyfromlistquestion',
            name='item_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.itemset'),
        ),
    ]
