# Generated by Django 3.2 on 2023-04-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_auto_20230414_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manyfromlistquestion',
            name='answer_mode',
            field=models.IntegerField(choices=[(1, 'ONE'), (2, 'SOME')], default=1),
        ),
    ]
