# Generated by Django 3.2 on 2023-04-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_alter_manyfromlistquestion_answer_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manyfromlistquestion',
            name='answer_mode',
        ),
        migrations.AddField(
            model_name='manyfromlistquestion',
            name='multiple_choices',
            field=models.BooleanField(default=False),
        ),
    ]
