# Generated by Django 3.2 on 2023-04-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0016_auto_20230425_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='manyfromlistquestion',
            name='use_points',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='use_points',
            field=models.BooleanField(default=False),
        ),
    ]
