# Generated by Django 3.2 on 2023-04-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0017_auto_20230426_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manyfromlistquestion',
            name='use_points',
        ),
        migrations.AddField(
            model_name='itemset',
            name='use_points',
            field=models.BooleanField(default=False),
        ),
    ]
