# Generated by Django 3.2 on 2023-04-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0018_auto_20230426_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveypassing',
            name='age',
        ),
        migrations.RemoveField(
            model_name='surveypassing',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='surveypassing',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='surveypassing',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='surveypassing',
            name='status',
        ),
        migrations.RemoveField(
            model_name='surveypassing',
            name='survey_title',
        ),
        migrations.RemoveField(
            model_name='surveypassing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='surveypassing',
            name='user_name',
        ),
        migrations.AddField(
            model_name='surveypassing',
            name='answers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='surveypassing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
