# Generated by Django 3.2 on 2023-01-07 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0031_auto_20221219_1648'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doc_uuid', models.UUIDField(editable=False, null=True, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Дата загрузки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='projects.project')),
                ('user_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_changer', to=settings.AUTH_USER_MODEL, verbose_name='user_update')),
            ],
        ),
        migrations.CreateModel(
            name='TagForDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='document.document')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('content', models.TextField(verbose_name='контент')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element', to='document.document')),
            ],
        ),
    ]
