# Generated by Django 3.2 on 2023-01-18 18:25

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0003_alter_document_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='document',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2012-09-04 06:00', verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_modified_user',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='document',
            name='tag_color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Plate color'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
