# Generated by Django 3.2 on 2023-01-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20230118_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='published',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user_update',
        ),
    ]
