# Generated by Django 3.2 on 2023-01-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20230119_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['position']},
        ),
    ]
