# Generated by Django 3.2 on 2023-01-31 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20230129_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='project',
            new_name='host_project',
        ),
    ]
