# Generated by Django 3.2 on 2023-02-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_rename_project_document_host_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='element',
            name='position',
        ),
    ]
