# Generated by Django 3.2 on 2023-02-13 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_auto_20230202_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='document.document', verbose_name='Родитель'),
        ),
    ]
