# Generated by Django 3.2 on 2023-02-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_document_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(default='', verbose_name='Контент'),
        ),
    ]
