# Generated by Django 3.2 on 2023-03-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_document_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['created_at']},
        ),
    ]
