# Generated by Django 3.2 on 2023-03-06 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20230214_1208'),
        ('document', '0014_alter_document_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='host_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project'),
        ),
    ]
