# Generated by Django 3.2 on 2023-03-15 12:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_alter_document_host_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(null=True), blank=True, default=list, size=None, verbose_name='Document order'),
        ),
    ]
