# Generated by Django 3.2 on 2022-06-01 05:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='№')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('code', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='code')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждён')),
                ('is_active', models.BooleanField(default=True, help_text='Определяет, следует ли считать этого пользователя активным.Снимите этот флажок вместо удаления учетных записей.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Определяет, может ли пользователь войти как администратор.', verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, help_text='Определяет, может ли пользователь войти как суперюзер.', verbose_name='superuser status')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['pkid'],
            },
        ),
    ]
