# Generated by Django 3.2 on 2022-06-28 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        ('accounts', '0004_auto_20220613_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription', verbose_name='Subscription info'),
        ),
    ]
