# Generated by Django 3.2 on 2022-07-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
    ]
