# Generated by Django 3.2 on 2022-07-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='b24_contact_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='b24_deal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
