# Generated by Django 3.2 on 2022-10-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220810_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Like'),
        ),
    ]
