# Generated by Django 3.2 on 2022-10-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_invited',
            field=models.BooleanField(default=False, verbose_name='Is invited'),
        ),
    ]
