# Generated by Django 3.2 on 2022-11-02 09:37

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20221025_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disk_space',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Used disk space'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=accounts.utils.get_upload_path, verbose_name='Avatar'),
        ),
    ]
