# Generated by Django 3.2 on 2022-12-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20221102_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_like',
            field=models.BooleanField(default=False, verbose_name='Promo document like'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Promo bordomatic like'),
        ),
    ]
