# Generated by Django 3.2 on 2022-12-08 05:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20221201_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
    ]
