# Generated by Django 3.2 on 2023-02-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_contacts_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='changed_password_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='changed_password_date'),
        ),
    ]
