# Generated by Django 3.2 on 2023-02-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='changed_password_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='changed_password_date'),
        ),
    ]
