# Generated by Django 3.2 on 2022-06-01 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('sortOrder', models.PositiveBigIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('in_trash_since', models.DateTimeField(blank=True, null=True)),
                ('tagColor', models.CharField(blank=True, default='',
                                              max_length=20)),
                ('name', models.CharField(default='Вызывной', max_length=50)),
                ('date', models.DateField()),
                ('filmDay', models.CharField(blank=True, default='', max_length=20)),
                ('startTime', models.TimeField(blank=True, default='00:00')),
                ('endTime', models.TimeField(blank=True, default='00:00')),
                ('breakStart', models.TimeField(blank=True, default='00:00')),
                ('breakEnd', models.TimeField(blank=True, default='00:00')),
                ('currentLunch', models.TimeField(blank=True, default='00:00')),
                ('shiftType', models.CharField(choices=[('interior', 'Интерьер'), ('exterior', 'Экстерьер')], default='interior', max_length=8)),
                ('comments', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'km_callsheets',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sortOrder', models.PositiveBigIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('in_trash_since', models.DateTimeField(blank=True, null=True)),
                ('tagColor', models.CharField(blank=True, default='',
                                              max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('checkIn', models.TimeField(blank=True, default='00:00')),
                ('checkOut', models.TimeField(blank=True, default='00:00')),
                ('startMotor', models.TimeField(blank=True, default='00:00')),
                ('stopMotor', models.TimeField(blank=True, default='00:00')),
                ('shiftType', models.CharField(choices=[('interior', 'Интерьер'), ('exterior', 'Экстерьер')], default='interior', max_length=8)),
                ('host_callsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='callsheets.callsheet')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userfields', models.ManyToManyField(blank=True, to='common.UserFieldMap')),
            ],
            options={
                'db_table': 'km_cs_locations',
                'ordering': ['sortOrder', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LocationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='callshets/location_maps/')),
                ('host_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='callsheets.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'km_cs_loc_maps',
            },
        ),
        migrations.CreateModel(
            name='CSLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('host_callsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='css_logos', to='callsheets.callsheet')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'km_cs_logos',
            },
        ),
    ]
