# Generated by Django 3.2 on 2022-06-01 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callsheets', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='host_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callsheets', to='projects.project'),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='userfields',
            field=models.ManyToManyField(blank=True, related_name='in_callsheet', to='common.UserFieldMap'),
        ),
    ]
