# Generated by Django 3.2 on 2022-06-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='sortOrder',
        ),
        migrations.RemoveField(
            model_name='location',
            name='sortOrder',
        ),
    ]
