# Generated by Django 3.2 on 2022-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0003_auto_20220603_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmap',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='callsheets/location_maps/'),
        ),
    ]
