# Generated by Django 3.2 on 2022-06-05 16:30
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0004_alter_locationmap_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cslogo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='callsheets/logos/'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='userfields',
            field=models.ManyToManyField(blank=True, to='common.UserFieldMap'),
        ),
        migrations.AlterField(
            model_name='cslogo',
            name='host_callsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='callsheet_logos',
                                    to='callsheets.callsheet'),
        ),
    ]
