# Generated by Django 3.2 on 2022-06-08 10:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0005_alter_cslogo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='colOrder',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='frameOrder',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='location',
            name='colOrder',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='location',
            name='frameOrder',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None),
        ),
    ]
