# Generated by Django 3.2 on 2022-06-13 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0007_auto_20220613_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsheet',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='callsheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='breakEnd',
            field=models.TimeField(blank=True, default='00:00', verbose_name='Lunch end'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='breakStart',
            field=models.TimeField(blank=True, default='00:00', verbose_name='Lunch start'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='currentLunch',
            field=models.TimeField(blank=True, default='00:00', verbose_name='Current lunch'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='endTime',
            field=models.TimeField(blank=True, default='00:00', verbose_name='Finish time'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='filmDay',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Film day number'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='in_trash_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='is_in_trash',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified at'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='last_modified_user',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='shiftType',
            field=models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], default='interior', max_length=8, verbose_name='Shift type'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='startTime',
            field=models.TimeField(blank=True, default='00:00', verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='tagColor',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Plate color'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='checkIn',
            field=models.TimeField(blank=True, default='00:00', verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='location',
            name='checkOut',
            field=models.TimeField(blank=True, default='00:00', verbose_name='Check-out'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='in_trash_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_in_trash',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='location',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified at'),
        ),
        migrations.AlterField(
            model_name='location',
            name='last_modified_user',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='location',
            name='shiftType',
            field=models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], default='interior', max_length=8, verbose_name='Shift type'),
        ),
        migrations.AlterField(
            model_name='location',
            name='startMotor',
            field=models.TimeField(blank=True, default='00:00', verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='location',
            name='stopMotor',
            field=models.TimeField(blank=True, default='00:00', verbose_name='Cut'),
        ),
        migrations.AlterField(
            model_name='location',
            name='tagColor',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Plate color'),
        ),
    ]
