# Generated by Django 3.2 on 2022-06-17 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_remove_contact_userfields'),
        ('callsheets', '0009_auto_20220613_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallsheetMember',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.contact')),
                ('host_callsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callsheets.callsheet')),
                ('userfields', models.ManyToManyField(blank=True, related_name='in_callsheets', to='contacts.Contact')),
            ],
            options={
                'db_table': 'ppm_callsheets_members',
            },
            bases=('contacts.contact', models.Model),
        ),
    ]
