# Generated by Django 3.2 on 2022-06-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20220613_0614'),
        ('callsheets', '0010_auto_20220617_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsheet',
            name='comments',
        ),
        migrations.AddField(
            model_name='callsheet',
            name='contacts',
            field=models.TextField(blank=True, default='', verbose_name='Contacts'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='userfields',
            field=models.ManyToManyField(blank=True, related_name='of_callsheet', to='common.UserFieldMap'),
        ),
    ]
