# Generated by Django 3.2 on 2022-06-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_remove_contact_userfields'),
        ('callsheets', '0011_auto_20220617_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheetmember',
            name='host_callsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='callsheets.callsheet'),
        ),
        migrations.AlterField(
            model_name='callsheetmember',
            name='userfields',
            field=models.ManyToManyField(blank=True, related_name='of_callsheets', to='contacts.Contact'),
        ),
    ]
