# Generated by Django 3.2 on 2022-06-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20220613_0614'),
        ('callsheets', '0014_callsheetmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheetmember',
            name='userfields',
            field=models.ManyToManyField(blank=True, related_name='of_callsheets', to='common.UserFieldMap'),
        ),
    ]
