# Generated by Django 3.2 on 2022-06-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0015_alter_callsheetmember_userfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheetmember',
            name='sunrise',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='callsheetmember',
            name='sunset',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='callsheetmember',
            name='weather',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
