# Generated by Django 3.2 on 2022-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_rename_field_usercell_column'),
        ('callsheets', '0016_auto_20220618_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheetmember',
            name='userfields',
            field=models.ManyToManyField(blank=True, related_name='of_callsheetmember', to='common.UserCell'),
        ),
    ]
