# Generated by Django 3.2 on 2022-06-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20220618_1152'),
        ('callsheets', '0017_alter_callsheetmember_userfields'),
    ]

    operations = [

    ]
