# Generated by Django 3.2 on 2022-06-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20220618_1152'),
        ('callsheets', '0019_remove_callsheet_userfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='usercolumns',
            field=models.ManyToManyField(blank=True, related_name='in_callsheet', to='common.UserColumn'),
        ),
    ]
