# Generated by Django 3.2 on 2022-06-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20220618_1152'),
        ('callsheets', '0020_auto_20220619_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheet',
            name='usercolumns',
            field=models.ManyToManyField(blank=True, related_name='of_callsheet', to='common.UserColumn'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='userfields',
            field=models.ManyToManyField(blank=True, related_name='in_callsheet', to='common.UserCell'),
        ),
    ]
