# Generated by Django 3.2 on 2022-06-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20220618_1152'),
        ('callsheets', '0021_auto_20220619_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='usercolumns',
            field=models.ManyToManyField(blank=True, related_name='of_location', to='common.UserColumn'),
        ),
        migrations.AlterField(
            model_name='location',
            name='userfields',
            field=models.ManyToManyField(blank=True, related_name='in_location', to='common.UserCell'),
        ),
    ]
