# Generated by Django 3.2 on 2022-06-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20220618_1152'),
        ('callsheets', '0022_auto_20220619_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheetmember',
            name='usercolumns',
            field=models.ManyToManyField(blank=True, related_name='of_callsheetmember', to='common.UserColumn'),
        ),
        migrations.AlterField(
            model_name='callsheetmember',
            name='userfields',
            field=models.ManyToManyField(blank=True, related_name='in_callsheetmember', to='common.UserCell'),
        ),
    ]
