# Generated by Django 3.2 on 2022-06-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20220618_1152'),
        ('callsheets', '0023_auto_20220619_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsheetmember',
            name='usercolumns',
        ),
        migrations.AddField(
            model_name='callsheet',
            name='member_columns',
            field=models.ManyToManyField(blank=True, related_name='of_callsheetmember', to='common.UserColumn'),
        ),
    ]
