# Generated by Django 3.2 on 2022-06-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0024_auto_20220619_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsheetmember',
            name='sunrise',
        ),
        migrations.RemoveField(
            model_name='callsheetmember',
            name='sunset',
        ),
        migrations.RemoveField(
            model_name='callsheetmember',
            name='weather',
        ),
        migrations.AddField(
            model_name='callsheet',
            name='sunrise',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='sunset',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='weather',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
