# Generated by Django 3.2 on 2022-06-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0025_auto_20220619_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsheet',
            name='contacts',
        ),
        migrations.AddField(
            model_name='callsheet',
            name='contact',
            field=models.TextField(blank=True, default='', verbose_name='Contact'),
        ),
    ]
