# Generated by Django 3.2 on 2022-06-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0027_auto_20220625_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callsheet',
            options={'verbose_name': 'Callsheet', 'verbose_name_plural': 'Callsheets'},
        ),
        migrations.AlterModelOptions(
            name='callsheetlogo',
            options={'verbose_name': 'Callsheet logo', 'verbose_name_plural': 'Callsheet logos'},
        ),
        migrations.AlterModelOptions(
            name='callsheetmember',
            options={'verbose_name': 'Callsheet member', 'verbose_name_plural': 'Callsheet members'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='locationmap',
            options={'verbose_name': 'Location map', 'verbose_name_plural': 'Location maps'},
        ),
    ]
