# Generated by Django 3.2 on 2022-06-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20220630_0536'),
        ('callsheets', '0028_auto_20220626_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheetmember',
            name='userfields',
            field=models.ManyToManyField(blank=True, related_name='of_callsheetmember', to='common.UserCell'),
        ),
    ]
