# Generated by Django 3.2 on 2022-07-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0030_auto_20220702_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callsheet',
            old_name='is_in_trash',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='callsheet',
            old_name='in_trash_since',
            new_name='deleted_since',
        ),
        migrations.RenameField(
            model_name='callsheetlogo',
            old_name='is_in_trash',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='callsheetlogo',
            old_name='in_trash_since',
            new_name='deleted_since',
        ),
        migrations.RenameField(
            model_name='callsheetmember',
            old_name='is_in_trash',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='callsheetmember',
            old_name='in_trash_since',
            new_name='deleted_since',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='is_in_trash',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='in_trash_since',
            new_name='deleted_since',
        ),
        migrations.RenameField(
            model_name='locationmap',
            old_name='is_in_trash',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='locationmap',
            old_name='in_trash_since',
            new_name='deleted_since',
        ),
        migrations.AddField(
            model_name='callsheet',
            name='deleted_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='callsheetlogo',
            name='deleted_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='callsheetmember',
            name='deleted_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='location',
            name='deleted_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='locationmap',
            name='deleted_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Deleted by'),
        ),
    ]
