# Generated by Django 3.2 on 2022-08-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0031_auto_20220718_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmap',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='callsheets/location_maps/'),
        ),
    ]
