# Generated by Django 3.2 on 2022-08-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0032_alter_locationmap_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsheet',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='callsheetlogo',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='callsheetlogo',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='callsheetmember',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='callsheetmember',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='location',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='location',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='locationmap',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='locationmap',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='callsheet',
            name='deleted_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='callsheetlogo',
            name='deleted_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='callsheetmember',
            name='deleted_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='deleted_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='locationmap',
            name='deleted_id',
            field=models.UUIDField(null=True),
        ),
    ]
