# Generated by Django 3.2 on 2022-08-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0033_auto_20220816_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheet',
            name='current_lunch',
            field=models.CharField(blank=True, default='00:00', max_length=100, verbose_name='Current lunch'),
        ),
    ]
