# Generated by Django 3.2 on 2022-08-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0035_auto_20220829_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheetmember',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
