# Generated by Django 3.2 on 2022-08-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0036_alter_callsheetmember_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheetmember',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
