# Generated by Django 3.2 on 2022-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0037_alter_callsheetmember_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheetmember',
            name='email',
            field=models.EmailField(blank=True, default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callsheetmember',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callsheetmember',
            name='phone',
            field=models.CharField(blank=True, default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
