# Generated by Django 3.2 on 2022-09-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0038_auto_20220829_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsheet',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='shift_type',
        ),
    ]
