# Generated by Django 3.2 on 2022-09-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0039_auto_20220902_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='shift_type',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Shift type'),
        ),
        migrations.AddField(
            model_name='location',
            name='shift_type',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Shift type'),
        ),
    ]
