# Generated by Django 3.2 on 2022-09-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0040_auto_20220902_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsheet',
            name='current_lunch',
        ),
        migrations.AddField(
            model_name='callsheet',
            name='lunch_type',
            field=models.CharField(blank=True, choices=[('c', 'Current'), ('h', 'Hour')], default='', max_length=1),
        ),
    ]
