# Generated by Django 3.2 on 2022-09-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0041_auto_20220909_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsheet',
            name='break_end',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='break_start',
        ),
        migrations.AddField(
            model_name='callsheet',
            name='lunch_time',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Lunch time'),
        ),
    ]
