# Generated by Django 3.2 on 2022-10-20 18:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_auto_20221020_1827'),
        ('callsheets', '0042_auto_20220909_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheet',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='host_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callsheets', to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='lunch_type',
            field=models.CharField(blank=True, choices=[('c', 'Current'), ('h', 'Hour')], default='', max_length=1, verbose_name='Lunch type'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='name',
            field=models.CharField(default='Callsheet', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='sunrise',
            field=models.TimeField(default='00:00', verbose_name='Sunrise'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='sunset',
            field=models.TimeField(default='00:00', verbose_name='Sunset'),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='weather',
            field=models.CharField(blank=True, max_length=200, verbose_name='Weather'),
        ),
        migrations.AlterField(
            model_name='callsheetlogo',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='callsheetlogo',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='callsheetlogo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='callsheets/logos/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='callsheetlogo',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AlterField(
            model_name='callsheetlogo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='callsheetmember',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='callsheetmember',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='callsheetmember',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AlterField(
            model_name='location',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='location',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='location',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AlterField(
            model_name='locationmap',
            name='col_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Column order'),
        ),
        migrations.AlterField(
            model_name='locationmap',
            name='deleted_id',
            field=models.UUIDField(null=True, verbose_name='Deleted id'),
        ),
        migrations.AlterField(
            model_name='locationmap',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='callsheets/location_maps/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='locationmap',
            name='frame_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Frame order'),
        ),
        migrations.AlterField(
            model_name='locationmap',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
