# Generated by Django 3.2 on 2022-10-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0043_auto_20221020_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='doc_uuid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
