# Generated by Django 3.2 on 2022-10-31 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0044_callsheet_doc_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callsheet',
            options={'ordering': ['id'], 'verbose_name': 'Callsheet', 'verbose_name_plural': 'Callsheets'},
        ),
    ]
