# Generated by Django 3.2 on 2022-11-02 12:03

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0045_alter_callsheet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheetlogo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=utils.get_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='locationmap',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=utils.get_upload_path, verbose_name='File'),
        ),
    ]
