# Generated by Django 3.2 on 2022-11-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0045_alter_callsheet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='max_temp',
            field=models.CharField(default='0', max_length=20, verbose_name='Max temperature'),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='min_temp',
            field=models.CharField(default='0', max_length=20, verbose_name='Min temperature'),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='temp',
            field=models.CharField(default='0', max_length=20, verbose_name='Temperature'),
        ),
    ]
