# Generated by Django 3.2 on 2022-11-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0046_auto_20221105_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='lng',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Longitude'),
        ),
    ]
