# Generated by Django 3.2 on 2022-11-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0046_auto_20221102_1503'),
        ('callsheets', '0047_auto_20221109_1330'),
    ]

    operations = [
    ]
