# Generated by Django 3.2 on 2022-11-18 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0050_auto_20221118_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheet',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
