# Generated by Django 3.2 on 2022-11-23 12:49

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0051_auto_20221118_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheetlogo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=utils.get_doc_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='locationmap',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=utils.get_doc_upload_path, verbose_name='File'),
        ),
    ]
