# Generated by Django 3.2 on 2022-11-29 09:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0052_auto_20221123_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsheet',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='callsheetlogo',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='callsheetmember',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='location',
            name='frame_order',
        ),
        migrations.RemoveField(
            model_name='locationmap',
            name='frame_order',
        ),
        migrations.AddField(
            model_name='callsheet',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='callsheetlogo',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='callsheetmember',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='location',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
        migrations.AddField(
            model_name='locationmap',
            name='data_row_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None, verbose_name='Data row order'),
        ),
    ]
