# Generated by Django 3.2 on 2023-04-17 09:14

import django.contrib.postgres.fields
from django.db import migrations, models
import testform.schema.utils
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='testform',
            name='testform_owner_i_d4750d_idx',
        ),
        migrations.RemoveField(
            model_name='basetfquestion',
            name='type_answer',
        ),
        migrations.RemoveField(
            model_name='finaltfquestion',
            name='answer',
        ),
        migrations.AddField(
            model_name='basetfquestion',
            name='answer_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('text', 'text'), ('video', 'video')], max_length=10), default=testform.schema.utils.get_answer_type_default, size=2),
        ),
        migrations.AddField(
            model_name='finaltfquestion',
            name='button_name',
            field=models.CharField(blank=True, default='Новый ответ', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='testformquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.get_doc_upload_path),
        ),
        migrations.AddField(
            model_name='testformquestion',
            name='logo_question',
            field=models.CharField(blank=True, choices=[('image', 'photo'), ('url', 'video')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testformquestion',
            name='url_name',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testform',
            name='time_to_answer',
            field=models.PositiveIntegerField(default=120, verbose_name='duration by test'),
        ),
        migrations.AlterField(
            model_name='testformquestion',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='question text'),
        ),
        migrations.AlterField(
            model_name='testformquestion',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='question description'),
        ),
        migrations.AlterField(
            model_name='testformquestion',
            name='question_type',
            field=models.CharField(choices=[('BaseTFQuestion', 'общий'), ('FinalTFQuestion', 'завершающий экран')], default='BaseTFQuestion', max_length=100, verbose_name='question type'),
        ),
        migrations.AddIndex(
            model_name='testform',
            index=models.Index(fields=['owner', 'id'], name='testform_owner_i_af5e8b_idx'),
        ),
    ]
