# Generated by Django 3.2 on 2022-06-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectpermissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpermission',
            table='km_object_permissions',
        ),
    ]
