# Generated by Django 3.2 on 2022-06-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectpermissions', '0002_alter_userpermission_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpermission',
            table='ppm_object_permissions',
        ),
    ]
