# Generated by Django 3.2 on 2022-07-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectpermissions', '0004_alter_userpermission_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpermission',
            options={'verbose_name': 'Object permission', 'verbose_name_plural': 'Object permissions'},
        ),
    ]
